apiVersion: v1
kind: Pod
metadata:
  labels:
    run: curl
  name: curl
spec:
  containers:
    - image: curlimages/curl:latest
      name: curl
      command: ["/bin/sh", "-c"]
      args:
        - |
          while true; do 
            curl -I http://nginx-web.default/api;
            sleep 1;
          done
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
